# -*- coding: utf-8 -*-
"""CS335_PythonLab1_GabrielWright.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pAVUJu_PLbS8J7I-QSp6ivWfLYAusEIV
"""

name = "Gabriel Wright"
age = 23
ai_course = True
print("Name:", name)
print("Age in 5 years:", age + 4)
print("Is enrolled in CS 335 course?", ai_course)


topics = ["Logic", "Search", "NLP", "ML", "Bayesian Inference", "Semantic Search", "Vector Embeddings"]
for i, topic in enumerate(topics, start=1):
    print(f"{i}. We will study: {topic}")


student = {"name": "Gabriel", "score": 95}
if student["score"] >= 95:
    grade = "A+"
elif student["score"] >= 90:
    grade = "A"
elif student["score"] >= 80:
    grade = "B"
else:
    grade = "C or below"
print(f"{student['name']} received a grade of {grade}.")

def greet_student(name):
  return f"Welcome to Gabriel, {name}!"
# Test
print(greet_student("Gabriel"))
def square_number(num):
    return num ** 2
# Test square_number
print(square_number(4))
print(square_number(7))